max_seq_len: 2048
# global_seed: 17
model:
  name: mpt_causal_lm
  init_device: meta
  d_model: 1024
  n_heads: 16
  n_layers: 24
  expansion_ratio: 4
  max_seq_len: 2048
  vocab_size: 50368
  loss_fn: torch_crossentropy
  attn_config:
    attn_impl: flash
tokenizer:
  name: EleutherAI/gpt-neox-20b
  kwargs:
    model_max_length: 2048
train_loader:
  name: text
  dataset:
    local: /home/jupyter/llm-foundry4/WM_M_data/train
    split: train
    shuffle: true
    max_seq_len: 2048
    shuffle_seed: 17
  drop_last: true
  num_workers: 8
eval_loader:
  name: text
  dataset:
    local: /home/jupyter/llm-foundry4/WM_M_data/val
    split: valid
    shuffle: false
    max_seq_len: 2048
    shuffle_seed: 17
  drop_last: false
  num_workers: 8
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1
optimizer:
  name: decoupled_adamw
  lr: 0.0003
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0
algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0
max_duration: 3ep
eval_interval: 1
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 192
seed: 17
device_eval_batch_size: 8
device_train_microbatch_size: auto
precision: amp_bf16
fsdp_config:
  sharding_strategy: NO_SHARD
  mixed_precision: PURE
  activation_checkpointing: false
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true
progress_bar: false
log_to_console: true
console_log_interval: 1ba
callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}
loggers:
  tensorboard:
    log_dir: /home/jupyter/llm-foundry4/logs
# hydra:
#   run:
#     dir: /home/jupyter/calm/model_runs/pretrain/small_combined_dataset_60K_2/hydra
save_interval: 1ep
save_num_checkpoints_to_keep: 3
save_folder: /home/jupyter/llm-foundry4/saved_model
save_filename: original_model.pt
run_name: arup-test-mpt-small_combined_dataset_2
